FROM redis

COPY ./deftr--server/mounts/redis/config/redis.conf /usr/local/etc/redis/redis.conf
COPY ./deftr--server/mounts/redis/scripts /scripts

EXPOSE 6379

ENTRYPOINT [ "bash", "-c", "/scripts/init.sh" ]